### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by ng-hai** [themerdev/themer#116]
# Description
I'm trying to generate `block-wave` wallpaper, but got the error `MODULE_NOT_FOUND`

# To reproduce
1. Clone this repo https://github.com/ng-hai/hyper-rose-pine-next
2. Install package
  ```
  yarn install
  ```
3. Run `yarn wallpaper:dark`

## Screenshots
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/19520278/134311317-03f27d2d-b1c1-45f7-8e29-dcacee010162.png">

## Expected behavior
The build has no error

# Environment information

## CLI

Please fill out the following information if you are using the command-line interface. For the web UI, you can delete this section.

- Device [e.g. iPhone6, MacBook Pro]: Mac Mini M1
- OS [e.g. iOS, macOS]: macOS
- OS version [e.g. 14.0]: 12.0 Beta (21A5506j)
- Node version [e.g. 14.4.0]: 14.17.0
- `themer` version [e.g. 3.3.4]: 3.3.9
- Other `themer` packages and their versions [e.g. `@themerdev/vscode@2.2.1`]: @themerdev/wallpaper-block-wave@4.0.3

**Comment by mjswensen** [comment]
Thanks for the report, @ng-hai , taking a look now.

**Comment by mjswensen** [comment]
@ng-hai , I was able to run the commands successfully on a fresh clone:

![image](https://user-images.githubusercontent.com/1591879/134347611-fe8b2806-6048-4fc2-92e0-b65ff1a72490.png)

I am thinking that there were some issues with `node-gyp`/`node-canvas` over the last 24 hours or so—my CI was failing with random `403` errors trying to fetch the precompiled binaries from GitHub (even though they were there in the UI). 🤷  I would say give it some time and try again.

**Comment by mjswensen** [comment]
You might consider deleting `node_modules` and re-running `yarn` to see if that fixes the issue.

**Comment by ng-hai** [comment]
Thank you @mjswensen, let me try.

**Comment by mjswensen** [comment]
(BTW, hyper-rose-pine-next is gorgeous 🤩)

**Comment by ng-hai** [comment]
I have figured out the problem (have reinstalled VSCode, Hyper, Homebrew, NVM, and even been thinking to reinstall the OS because of Apple Silicon chip 🥵).

After so many failed attempts, I opened my Mac Air which using Intel chip to make a final one. And turned out, it was the config `--ignore-scripts` living in global `.yarnrc`. It makes the `yarn install` step missing optional dependencies, leading to this issue. How dumb was I.

**Comment by mjswensen** [comment]
Ooof, that's a painful one. Good find. 😅

**Comment by ng-hai** [comment]
I have added some dynamic wallpapers with higher resolution thanks to your lib. You may want to check new readme file 😄

Please take my one-time sponsoring as a gift 🎁

**Comment by mjswensen** [comment]
😍  It looks fantastic!

And thank you so much! 🙏
